apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-kong-ingress
  namespace: jenkins
  annotations:
    konghq.com/strip-path: "false"
    konghq.com/preserve-host: "true"
    konghq.com/plugins: |
      jenkins-headers-fix
spec:
  ingressClassName: kong
  rules:
  - host: jenkins.k8s.local
    http:
      paths:
      - path: /jenkins
        pathType: Prefix
        backend:
          service:
            name: jenkins
            port:
              number: 8080
  - http:
      paths:
      - path: /jenkins
        pathType: Prefix
        backend:
          service:
            name: jenkins
            port:
              number: 8080
---
# Kong Plugin: Proper reverse proxy headers cho Jenkins (ROOT CAUSE FIX)
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: jenkins-headers-fix
  namespace: jenkins
config:
  add:
    headers:
    - "X-Forwarded-Host:192.168.0.154:30080"
    - "X-Forwarded-Proto:http" 
    - "X-Forwarded-Port:30080"
plugin: request-transformer