apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-kong-ingress
  namespace: jenkins
  annotations:
    konghq.com/strip-path: "false"
    konghq.com/preserve-host: "false"
    konghq.com/plugins: jenkins-fix-host
spec:
  ingressClassName: kong
  rules:
  # Rule for domain access
  - host: jenkins.k8s.local
    http:
      paths:
      - path: /jenkins
        pathType: Prefix
        backend:
          service:
            name: jenkins
            port:
              number: 8080
  # Rule for IP-based access
  - http:
      paths:
      - path: /jenkins
        pathType: Prefix
        backend:
          service:
            name: jenkins
            port:
              number: 8080
---
# Kong Plugin chỉ fix Host header với port
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: jenkins-fix-host
  namespace: jenkins
config:
  add:
    headers:
    - "X-Forwarded-Port:30080"
    - "X-Forwarded-Proto:http"
  replace:
    headers:
    - "Host:192.168.0.154:30080"
plugin: request-transformer