apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkins.fullname" . }}
  namespace: {{ .Values.namespace | default "jenkins" }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.agentPort }}
      targetPort: agent
      protocol: TCP
      name: agent
  selector:
    {{- include "jenkins.selectorLabels" . | nindent 4 }}
